name: exchange_rate_app
description: "An app to check currency rates."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.6
  http: ^1.2.1
  get: ^4.6.6
  go_router: ^13.2.0
  shared_preferences: ^2.2.2
  fluttertoast: ^8.2.4
  connectivity_plus: ^5.0.2
  get_storage: ^2.1.1
  json_serializable: ^6.7.1
  modal_bottom_sheet: ^2.1.2
  provider: ^6.1.2
  flutter_screenutil: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Hlvetica
      fonts:
        - asset: assets/fonts/HelveticaNeue-W20-45-Light.ttf
    - family: Hlvetica
      fonts:
        - asset: assets/fonts/helvetica-neue-lt-arabic-75-bold.ttf
